spring:
  application:
    name: SmartJob-backend
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
server:
  port: ${SERVER_PORT}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sysu.smartjob.entity
  configuration:
    map-underscore-to-camel-case: true
com:
  jwt:
    user-secret-key: ${KEY}
    user-ttl: ${TTL}
    user-token-name: authentication
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${API_KEY}
      embedding-model:
        model-name: text-embedding-v4
        api-key: ${API_KEY}
      streaming-chat-model:
        model-name: qwen-max
        api-key: ${API_KEY}
bigmodel:
  api-key: ${MODEL_KEY}

