spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8080
com:
  jwt:
    user-secret-key: ThisIsASecretKeyWithMoreThan32CharactersLong123456
    user-ttl: 7200000
    user-token-name: authentication
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-c785a2a9342b44499951a049b8820449
      embedding-model:
        api-key: sk-c785a2a9342b44499951a049b8820449
      streaming-chat-model:
        api-key: sk-c785a2a9342b44499951a049b8820449
bigmodel:
  api-key: 20704d2c334e4f8a9c6e4532dfe7d932.DvjrbXQBqSHCcsOT