spring:
  # 测试环境配置
  profiles:
    active: test
  
  # 使用内存数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  # Redis配置（禁用）
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms
      
  # RabbitMQ配置（禁用）
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
# 日志配置
logging:
  level:
    com.sysu.smartjob: DEBUG
    org.springframework: WARN
    org.mybatis: DEBUG